# Generated by Django 3.2.7 on 2022-08-31 14:03

import datetime
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoUniPreGrado', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 34, 33064))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='172.168.5.202', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Calificativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 34, 37062))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='172.168.5.202', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Calificativos',
            },
        ),
        migrations.CreateModel(
            name='ConceptoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 34, 31065))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='172.168.5.202', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Conceptos de Pagos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('credito', models.IntegerField()),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 34, 32065))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='172.168.5.202', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='DetalleMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedioTrabajos', models.FloatField(blank=True, null=True)),
                ('examenParcial', models.FloatField(blank=True, null=True)),
                ('examenFinal', models.FloatField(blank=True, null=True)),
                ('promedioFinal', models.FloatField(blank=True, null=True)),
                ('retirado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 34, 36062))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='172.168.5.202', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Detalle de Matriculas',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 34, 34064))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='172.168.5.202', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='EstadoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 34, 30067))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='172.168.5.202', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Estados Academico',
            },
        ),
        migrations.CreateModel(
            name='EstadoBoletaP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 34, 30067))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='172.168.5.202', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Estados Boletas Pagos',
            },
        ),
        migrations.CreateModel(
            name='Maestria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 34, 31065))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='172.168.5.202', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Maestrias',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 34, 32065))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='172.168.5.202', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='ReporteEcoConceptoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('numeroRecibo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 34, 39061))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='172.168.5.202', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
                ('conceptoPago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.conceptopago')),
                ('estadoBoletaPago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.estadoboletap')),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 34, 30067))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='172.168.5.202', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo de Documentos',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 34, 27058))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='172.168.5.202', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aulaWeb', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 34, 35063))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='172.168.5.202', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.curso')),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.docente')),
                ('maestria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.maestria')),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.periodo')),
            ],
            options={
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.CreateModel(
            name='ReporteEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 34, 38062))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='172.168.5.202', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.alumno')),
                ('conceptoPago', models.ManyToManyField(blank=True, through='posgradofimapp.ReporteEcoConceptoPago', to='posgradofimapp.ConceptoPago')),
            ],
            options={
                'verbose_name_plural': 'Reportes Economicos',
            },
        ),
        migrations.AddField(
            model_name='reporteecoconceptopago',
            name='reporteEconomico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.reporteeconomico'),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDocumento', models.CharField(max_length=100)),
                ('primerNombre', models.CharField(max_length=100)),
                ('segundoNombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 34, 33064))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='172.168.5.202', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
                ('tipoDocumento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.tipodocumento')),
            ],
            options={
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 34, 36062))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='172.168.5.202', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.alumno')),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.periodo')),
                ('seccion', models.ManyToManyField(blank=True, through='posgradofimapp.DetalleMatricula', to='posgradofimapp.Seccion')),
            ],
            options={
                'verbose_name_plural': 'Matriculas',
            },
        ),
        migrations.CreateModel(
            name='Graduado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloTesis', models.CharField(max_length=300)),
                ('fechaGraduado', models.DateField(blank=True, null=True)),
                ('asesor', models.CharField(max_length=200)),
                ('promedio', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 34, 37062))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='172.168.5.202', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.alumno')),
                ('calificativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.calificativo')),
                ('primerEspecialista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primerEspecialista_article_set', to='posgradofimapp.docente')),
                ('segundoEspecialista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segundoEspecialista_article_set', to='posgradofimapp.docente')),
            ],
            options={
                'verbose_name_plural': 'Graduados',
            },
        ),
        migrations.AddField(
            model_name='docente',
            name='maestria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.maestria'),
        ),
        migrations.AddField(
            model_name='docente',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.persona'),
        ),
        migrations.AddField(
            model_name='detallematricula',
            name='matricula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.matricula'),
        ),
        migrations.AddField(
            model_name='detallematricula',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.seccion'),
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 34, 34064))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='172.168.5.202', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.persona')),
            ],
            options={
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='estadoAcademico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.estadoacademico'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='maestria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.maestria'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='periodoDeIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.periodo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.persona'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('dni', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('usu_tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posgradofimapp.tipousuario')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
