# Generated by Django 3.2.7 on 2022-08-31 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradofimapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 41, 646464)),
        ),
        migrations.AlterField(
            model_name='calificativo',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 41, 650451)),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 41, 646464)),
        ),
        migrations.AlterField(
            model_name='conceptopago',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 41, 643466)),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 41, 644465)),
        ),
        migrations.AlterField(
            model_name='detallematricula',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 41, 649452)),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 41, 647464)),
        ),
        migrations.AlterField(
            model_name='estadoacademico',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 41, 642466)),
        ),
        migrations.AlterField(
            model_name='estadoboletap',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 41, 643466)),
        ),
        migrations.AlterField(
            model_name='graduado',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 41, 650451)),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 41, 644465)),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 41, 648463)),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 41, 645465)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 41, 645465)),
        ),
        migrations.AlterField(
            model_name='reporteecoconceptopago',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 41, 651451)),
        ),
        migrations.AlterField(
            model_name='reporteeconomico',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 41, 651451)),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 41, 647464)),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 41, 642466)),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 9, 3, 41, 640468)),
        ),
    ]
